# .travis.yml
language: node_js
node_js:
  - 14
install:
  - npm install
branches:
  only:
    - main
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - npm run build # Generate static HTML files
  - echo "scioxr.com" > build/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: main